// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArN0XcRAsxI35Hz1_Sq4XubFoficRCyFI',
    appId: '1:1019304995057:web:b8ff72f0a07061a2a22150',
    messagingSenderId: '1019304995057',
    projectId: 'flashchat-d5955',
    authDomain: 'flashchat-d5955.firebaseapp.com',
    databaseURL: 'https://flashchat-d5955-default-rtdb.firebaseio.com',
    storageBucket: 'flashchat-d5955.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAasviNVScl8dVIY-o2n5v9qMCzJ6SJSKw',
    appId: '1:1019304995057:android:4301bdeb79ac1e04a22150',
    messagingSenderId: '1019304995057',
    projectId: 'flashchat-d5955',
    databaseURL: 'https://flashchat-d5955-default-rtdb.firebaseio.com',
    storageBucket: 'flashchat-d5955.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChq-4BDcPZbHGiPfMkDppZOQrZRjUH_XQ',
    appId: '1:1019304995057:ios:b78fd9a85ebd0ef1a22150',
    messagingSenderId: '1019304995057',
    projectId: 'flashchat-d5955',
    databaseURL: 'https://flashchat-d5955-default-rtdb.firebaseio.com',
    storageBucket: 'flashchat-d5955.appspot.com',
    androidClientId: '1019304995057-74mnts2jdrefm38divldvqdfaancrs0v.apps.googleusercontent.com',
    iosClientId: '1019304995057-m3pffc4fukk397v4o3o2do30p0qqoh99.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChq-4BDcPZbHGiPfMkDppZOQrZRjUH_XQ',
    appId: '1:1019304995057:ios:b78fd9a85ebd0ef1a22150',
    messagingSenderId: '1019304995057',
    projectId: 'flashchat-d5955',
    databaseURL: 'https://flashchat-d5955-default-rtdb.firebaseio.com',
    storageBucket: 'flashchat-d5955.appspot.com',
    androidClientId: '1019304995057-74mnts2jdrefm38divldvqdfaancrs0v.apps.googleusercontent.com',
    iosClientId: '1019304995057-m3pffc4fukk397v4o3o2do30p0qqoh99.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArN0XcRAsxI35Hz1_Sq4XubFoficRCyFI',
    appId: '1:1019304995057:web:b603ca3693dd1096a22150',
    messagingSenderId: '1019304995057',
    projectId: 'flashchat-d5955',
    authDomain: 'flashchat-d5955.firebaseapp.com',
    databaseURL: 'https://flashchat-d5955-default-rtdb.firebaseio.com',
    storageBucket: 'flashchat-d5955.appspot.com',
  );

}